language: node_js
node_js:
- 6.6.0
cache:
  directories:
    - node_modules
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - wget "http://chromedriver.storage.googleapis.com/2.22/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
- npm install -g angular-cli
- (cd frontend && npm install)
script:
- (cd frontend && ng lint)
- (cd frontend && ng test --watch=false)
- (cd frontend && ng serve &)
- (cd frontend && ng e2e)
notifications:
  email:
  - stollenwerk@kitconcept.com
